main: groupChat.GroupChat
name: GroupChat
version: 2.0.1-1.21.1
description: GroupChat - Chat with your friends!
api-version: 1.21
Author: [Skullians, _NickVo]

commands:
  party:
    description: Primary command for the plugin
  p:
    description: Speak within a party
  confirm:
    description: Confirmation command for the plugin
